language: java

jdk:
  - oraclejdk8
  - oraclejdk9

sudo: required

install: true

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)

